=== narina-nikhil-39/BAKERS-CORNER/HTML/bakery.dtd
<!ELEMENT bakery (product+)>
<!ELEMENT product (name, category, price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== narina-nikhil-39/BAKERS-CORNER/HTML/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bakery SYSTEM "bakery.dtd">
<bakery>
    <product>
        <name>Chocolate Cake</name>
        <category>Cake</category>
        <price>500</price>
    </product>
    <product>
        <name>Black Forest Cake</name>
        <category>Cake</category>
        <price>600</price>
    </product>
    <product>
        <name>Donuts</name>
        <category>Bakery</category>
        <price>80</price>
    </product>
</bakery>
